### ISSUE TITLE
不是加了cocoaPods 导入，为什么我搜索不到

### ISSUE THREAD

**Issue by Kaizi-oo** [tencentyun/COS_iOS_SDK#10]
不是加了cocoaPods 导入，为什么我搜索不到！！！

**Comment by EricCheungSCUT** [comment]
可能是本地的索引没有更新，请执行
pod repo update
后再试一下

**Comment by Kaizi-oo** [comment]
Updating spec repo `master`
  $ /usr/local/bin/git -C /Users/yangkai/.cocoapods/repos/master fetch origin
  --progress
  remote: Counting objects: 7602, done.        
  remote: Compressing objects: 100% (172/172), done.        
  remote: Total 7602 (delta 3096), reused 3030 (delta 3030), pack-reused 4391        
  Receiving objects: 100% (7602/7602), 849.72 KiB | 190.00 KiB/s, done.
  Resolving deltas: 100% (5040/5040), completed with 1344 local objects.
  From https://github.com/CocoaPods/Specs
     d9227616d2c..63f0eae51de  master     -> origin/master
  $ /usr/local/bin/git -C /Users/yangkai/.cocoapods/repos/master rev-parse
  --abbrev-ref HEAD
  master
  $ /usr/local/bin/git -C /Users/yangkai/.cocoapods/repos/master reset --hard
  origin/master
  HEAD is now at 63f0eae51de [Add] YSTShareKit 0.2.1

[!] Unable to find a pod with name, author, summary, or description matching `QCloudCOSV4`

**Comment by EricCheungSCUT** [comment]
我这边是可以pod install的，如果觉得可能是没有发布到cocoapods的话，这个库是可以在cocoapods的官网上搜到 https://cocoapods.org/?q=QCloudCOSV4 。    

至于本地为什么搜不到其实已经超出了SDK的范围，可能这个SO上面的回答可以帮助到您。https://stackoverflow.com/questions/21342574/cocoapods-error-to-install-search-pods/21492886#21492886

**Comment by Kaizi-oo** [comment]
直接install的话，的确install了，然后通过 pod search命令还是没有。。。这样用吧，还是。
