### ISSUE TITLE
 +[COSClient uploadThread]: unrecognized selector sent to class 0x102346b68

### ISSUE THREAD

**Issue by kency** [tencentyun/COS_iOS_SDK#6]
直接按照首页的使用说明写的代码,参数都没问题,xcode 8.3.3 IOS Development Target 8.0 模拟器iphone6 IOS10.3

**Comment by yishuiliunian** [comment]
在Build Settings的Other Link Flag中假如-ObjC

**Comment by kency** [comment]
原来如此，直接post 给api传了
